#!/usr/bin/env python3
"""
Rebuild inputs/{periods,timeseries,timepoints}.csv for the 2020-2060
9-period horizon (plan decision D-8), and write docs/data_requirements.md
cataloging the fresh data needed in other inputs/*.csv files.

Idempotent: rerunning with the same constants produces identical files.

Per-period weight check is performed before writing:
  sum(ts_scale_to_period * ts_num_tps * ts_duration_of_tp) per period
  must be within ±1% of period_length_years * 8766 hours.

CAUTION: after this tool runs, inputs/ will be in a transitional state
(new time axis, old PERIOD-indexed data) and switch solve will fail
until docs/data_requirements.md is fulfilled. Use --dry-run first.

Usage:
  python tools/rebuild_periods.py --dry-run
  python tools/rebuild_periods.py
"""

import argparse
import csv
from pathlib import Path

# ---------- configuration (plan D-8: uniform 5-year periods, 2020-2060) ----------

PERIOD_LENGTH_YEARS = 5
PERIOD_STARTS = [2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060]

# 12 representative days per period, same canonical pattern applied to every
# period. Pattern is taken from upstream SWITCH-China period 2023 as a
# placeholder — when real load data is available, re-cluster and replace.
# (month, day, ts_scale_to_period)
#   scale ≈ days_in_that_month * PERIOD_LENGTH_YEARS
CANONICAL_REPDAYS = [
    ( 1, 22, 155.0),   # Jan (31 days × 5)
    ( 2,  8, 140.0),   # Feb (28 days × 5)
    ( 3, 21, 155.0),
    ( 4, 11, 150.0),
    ( 5, 22, 155.0),
    ( 6, 16, 150.0),
    ( 7, 22, 155.0),
    ( 8, 19, 155.0),
    ( 9, 20, 150.0),
    (10, 26, 155.0),
    (11, 19, 150.0),
    (12, 16, 155.0),
]

TP_PER_TS = 6   # 6 timepoints per representative day
TP_HOURS = 4    # 4 hours each → 24 hr/day

HOURS_PER_YEAR = 8766          # SWITCH convention (365.25 × 24)
WEIGHT_TOLERANCE = 0.01        # ±1%, matches switch_model/timescales.py:391-411


def period_mid_year(period_start):
    """Year used inside timeseries / timepoint IDs — middle of the period."""
    return period_start + (PERIOD_LENGTH_YEARS - 1) // 2  # 2020 -> 2022, 2025 -> 2027, ...


def build_periods_rows():
    rows = [("INVESTMENT_PERIOD", "period_start", "period_end")]
    for ps in PERIOD_STARTS:
        rows.append((ps, ps, ps + PERIOD_LENGTH_YEARS - 1))
    return rows


def build_timeseries_rows():
    rows = [("TIMESERIES", "ts_period", "ts_duration_of_tp", "ts_num_tps", "ts_scale_to_period")]
    for ps in PERIOD_STARTS:
        my = period_mid_year(ps)
        for m, d, scale in CANONICAL_REPDAYS:
            ts_id = f"{my}.{m:02d}.{d:02d}"
            rows.append((ts_id, ps, TP_HOURS, TP_PER_TS, scale))
    return rows


def build_timepoints_rows():
    rows = [("timepoint_id", "timestamp", "timeseries")]
    for ps in PERIOD_STARTS:
        my = period_mid_year(ps)
        for m, d, _ in CANONICAL_REPDAYS:
            ts_id = f"{my}.{m:02d}.{d:02d}"
            for h in range(0, 24, TP_HOURS):
                tp_id = f"{ts_id}.{h:02d}"
                timestamp = f"{my}-{m:02d}-{d:02d}_{h:02d}:00"
                rows.append((tp_id, timestamp, ts_id))
    return rows


def per_period_weight_check():
    """Return (actual_hours_per_period, expected_hours_per_period, drift_fraction)."""
    actual = sum(scale * TP_PER_TS * TP_HOURS for _, _, scale in CANONICAL_REPDAYS)
    expected = PERIOD_LENGTH_YEARS * HOURS_PER_YEAR
    drift = (actual - expected) / expected
    return actual, expected, drift


def write_csv(path, rows):
    with open(path, "w", newline="") as f:
        csv.writer(f).writerows(rows)


REQUIREMENTS_HEADER = """\
# Data requirements for the 2020-2060 time horizon

> **Generated by `tools/rebuild_periods.py`** — do not hand-edit the header;
> fill in the "Source" / "Filled?" columns below as data arrives.
>
> Lists every CSV field that needs fresh data when extending base inputs
> to the 9-period horizon (2020/2025/2030/2035/2040/2045/2050/2055/2060).
>
> Conventions:
> - Costs in **2020 USD** (plan decision D-7).
> - Tools never fabricate data; user provides values or names the source.

## Time-axis (already written by `tools/rebuild_periods.py`)

| File | Rows | Status |
|---|---|---|
| `inputs/periods.csv` | 9 | ✓ generated |
| `inputs/timeseries.csv` | 108 (9 periods × 12 representative days) | ✓ generated |
| `inputs/timepoints.csv` | 648 (108 ts × 6 timepoints) | ✓ generated |

## Period-indexed CSVs (need rows for the new periods)

| File | Index columns | Field(s) to fill | Source (you fill in) | Filled? |
|---|---|---|---|---|
| `inputs/gen_build_costs.csv` | GENERATION_PROJECT, build_year | gen_overnight_cost ($/kW, 2020 USD), gen_fixed_om ($/kW-yr), gen_storage_energy_overnight_cost ($/kWh, storage only) | — | — |
| `inputs/fuel_cost.csv` | load_zone, fuel, period | fuel_cost ($/MMBTU, 2020 USD) | — | — |
| `inputs/fuel_supply_curves.csv` | regional_fuel_market, period, tier | unit_cost ($/MMBTU, 2020 USD), max_avail_at_cost (MMBTU/period) | — | — |
| `inputs/carbon_policies.csv` | PERIOD | carbon_cap_tco2_per_yr (tCO2/yr), carbon_cost_dollar_per_tco2 ($/tCO2, 2020 USD) | — | — |
| `inputs/capacity_plans.csv` | energy_sources, load_zones, period | planned_capacity_mw (MW; minimum capacity target per province × tech) | — | — |
| `inputs/total_capacity_limits.csv` | energy_sources, period | total_capacity_limit_mw (MW; national ceiling; currently only Uranium) | — | — |
| `inputs/zone_coincident_peak_demand.csv` | LOAD_ZONE, PERIOD | zone_expected_coincident_peak_demand (MW) | — | — |

## Timepoint-indexed CSVs (648 timepoints per zone or per project)

| File | Index columns | Field(s) to fill | Source | Filled? |
|---|---|---|---|---|
| `inputs/loads.csv` | load_zone, TIMEPOINT | zone_demand_mw (MW) | — | — |
| `inputs/variable_capacity_factors.csv` | GENERATION_PROJECT, timepoint | gen_max_capacity_factor (0–1, per VRE project) | — | — |

## Timeseries-indexed CSVs (108 timeseries)

| File | Index columns | Field(s) to fill | Source | Filled? |
|---|---|---|---|---|
| `inputs/hydro_timeseries.csv` | hydro_project, timeseries | hydro_min_flow_mw, hydro_avg_flow_mw (MW) | — | — |

## Historical / typically unchanged

| File | Notes |
|---|---|
| `inputs/gen_info.csv` | Tech parameters; only needs new rows if introducing new project types (e.g., offshore wind floating). |
| `inputs/gen_build_predetermined.csv` | Historical fleet (pre-2020 build years). Consider whether to add 2020-2024 historical builds. |
| `inputs/gen_part_load_heat_rates.csv` | Tech-only, no time dimension. |
| `inputs/load_zones.csv` | Zone metadata; mostly stable. |
| `inputs/transmission_lines.csv` | Network topology; existing capacity unchanged. |
| `inputs/financials.csv` | **Update `base_financial_year` to 2020** (plan D-7). |

## How to log a data source

When you provide data for a field, edit the corresponding row above:

- Replace the `—` in "Source" with a short citation (doc title, URL, or local file path).
- Replace the `—` in "Filled?" with `✓ YYYY-MM-DD` after `tools/validate_scenario.py` passes for the affected scenarios.
"""


def write_requirements_md(path, actual, expected, drift):
    extra = (
        "\n## Per-period time-weight sanity check (auto-generated)\n\n"
        f"- Each period contributes `sum(ts_scale × ts_num_tps × ts_duration) = "
        f"{actual:.0f} hours`\n"
        f"- Expected for {PERIOD_LENGTH_YEARS}-year periods: "
        f"`{PERIOD_LENGTH_YEARS} × {HOURS_PER_YEAR} = {expected:.0f} hours`\n"
        f"- Drift: `{drift * 100:+.3f}%` (validation tolerance ±{WEIGHT_TOLERANCE * 100:.0f}%)\n"
    )
    with open(path, "w") as f:
        f.write(REQUIREMENTS_HEADER + extra)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--inputs-dir", default="inputs",
                        help="Inputs directory to write into (default: inputs)")
    parser.add_argument("--docs-dir", default="docs",
                        help="Where to write data_requirements.md (default: docs)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would change; write nothing")
    args = parser.parse_args()

    inputs_dir = Path(args.inputs_dir)
    docs_dir = Path(args.docs_dir)

    actual, expected, drift = per_period_weight_check()
    print(f"Per-period weight: {actual:.0f} hrs (expected {expected:.0f}, drift {drift*100:+.3f}%)")
    if abs(drift) > WEIGHT_TOLERANCE:
        raise SystemExit(
            f"FAIL: drift exceeds ±{WEIGHT_TOLERANCE*100:.0f}% — adjust CANONICAL_REPDAYS scales"
        )
    print("Weight check passed ✓")

    periods = build_periods_rows()
    timeseries = build_timeseries_rows()
    timepoints = build_timepoints_rows()

    print()
    print(f"Periods:    {len(periods) - 1} rows -> {inputs_dir / 'periods.csv'}")
    print(f"Timeseries: {len(timeseries) - 1} rows -> {inputs_dir / 'timeseries.csv'}")
    print(f"Timepoints: {len(timepoints) - 1} rows -> {inputs_dir / 'timepoints.csv'}")
    print(f"Docs:       data_requirements.md -> {docs_dir / 'data_requirements.md'}")

    if args.dry_run:
        print()
        print("--dry-run set; no files written.")
        return

    inputs_dir.mkdir(parents=True, exist_ok=True)
    docs_dir.mkdir(parents=True, exist_ok=True)
    write_csv(inputs_dir / "periods.csv", periods)
    write_csv(inputs_dir / "timeseries.csv", timeseries)
    write_csv(inputs_dir / "timepoints.csv", timepoints)
    write_requirements_md(docs_dir / "data_requirements.md", actual, expected, drift)

    print()
    print("Done.")
    print("Next steps:")
    print("  1. Review docs/data_requirements.md")
    print("  2. Provide data for the listed CSV fields (model will not build until then)")
    print("  3. Once data is filled, run tools/validate_scenario.py")


if __name__ == "__main__":
    main()
